# pane indexing
set -g renumber-windows on
setw -g pane-base-index 1

# splits
bind | split-window -h -c "#{pane_current_path}" -b
bind - split-window -v -c "#{pane_current_path}" -b
unbind '"'
unbind %

# colors
set -ga terminal-overrides ",*:Tc"

#misc
set -g repeat-time 300
